eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
  
spring:
  application:
    name: service-zuul
    
zuul:
  routes:
    api-a:
      path: /zuul-c1/**
      serviceId: service-consumer
    api-b:
      path: /zuul-c2/**
      serviceId: service-consumer-feign