eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9091
  
spring:
  application:
    name: service-provider
  zipkin:
      base-url: http://localhost:9411